### ISSUE TITLE
read DICOM headers

### ISSUE THREAD

**Issue by jonkoller** [BlackHershey/asl-scripts#1]
probably python code to read DICOM headers, return "Content Time" from SR series 99.

https://github.com/pydicom/pydicom

(0008,0033) | Content Time

From CNDA, download series 99 for MPD101 as test data.

Maybe loop over all series 99 files, check for "pcasl_3D_tgse_3mm_PLD2", output series number and Content Time.

**Comment by hacevedo** [comment]
Changes in commit https://github.com/BlackHershey/asl-scripts/commit/2ced2b8e8da98c3fdd1874316e20684b97860531
